language: node_js

matrix:
    include:
        - name: Test Ubuntu18.04 LTS + gcc
          os: linux
          dist: bionic
          sudo: required
          script:
              - sh scripts/travis_build.sh
    before_install:
        -eval "${MATRIX_EVAL}"
